import { PREFIX_CONST_REQUEST, CONST_REQUEST } from './base';

export const TODO = {
  ...PREFIX_CONST_REQUEST('SEARCH', 'TODO'),
};

export const APP = {
  ...CONST_REQUEST('LOADING', 'APP'),
  ...CONST_REQUEST('LEFTMENU_KEYS', 'APP'),
  ...CONST_REQUEST('LEFTMENU_POPVER', 'APP'),
  ...CONST_REQUEST('LEFTMENU_SWITCH', 'APP'),
};

export const CURRENTUSER = {
  ...PREFIX_CONST_REQUEST('LOGIN', 'CURRENTUSER'),
  ...PREFIX_CONST_REQUEST('LOGOUT', 'CURRENTUSER'),
  ...PREFIX_CONST_REQUEST('RENEW', 'CURRENTUSER'),
  ...PREFIX_CONST_REQUEST('CALLBACK', 'CURRENTUSER'),
};

export const CUSTOMER = {
  ...PREFIX_CONST_REQUEST('SEARCH', 'CUSTOMER'),
};

export const AGENT = {
  ...PREFIX_CONST_REQUEST('SEARCH', 'AGENT'),
};

export const OFFER = {
  ...PREFIX_CONST_REQUEST('SEARCH', 'OFFER'),
  ...PREFIX_CONST_REQUEST('CREATE', 'OFFER'),
  ...PREFIX_CONST_REQUEST('UPDATE', 'OFFER'),
  ...PREFIX_CONST_REQUEST('DELETE', 'OFFER'),
  ...PREFIX_CONST_REQUEST('DETAIL', 'OFFER'),
};
